package app.sterna.core.imap

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.BufferedReader
import java.io.InputStreamReader
import java.io.OutputStream
import java.net.Socket
import java.time.ZonedDateTime
import java.time.format.DateTimeFormatter
import java.util.Base64
import javax.net.ssl.SSLSocket
import javax.net.ssl.SSLSocketFactory

class SmtpException(message: String) : Exception(message)

/** A file attachment to include in an outgoing message. */
data class OutgoingAttachment(
    val name: String,
    val type: String,
    val bytes: ByteArray,
)

/** A message to submit over SMTP. Addresses are bare "name <addr>" or "addr" strings. */
data class OutgoingMessage(
    val from: String,
    val to: List<String>,
    val cc: List<String> = emptyList(),
    /** Blind-copy recipients: in the SMTP envelope (RCPT TO) but never in the headers. */
    val bcc: List<String> = emptyList(),
    val subject: String,
    val body: String,
    /** Optional HTML body; when set the message is sent as text/html. */
    val html: String? = null,
    val inReplyTo: String? = null,
    val references: String? = null,
    /** RFC 5322 Message-ID (without angle brackets); generated by the caller. */
    val messageId: String,
    /** Epoch millis for the Date header. */
    val dateMillis: Long,
    val attachments: List<OutgoingAttachment> = emptyList(),
)

/** Minimal SMTP submission client (EHLO, optional STARTTLS, AUTH, MAIL/RCPT/DATA). */
class SmtpClient {
    suspend fun send(config: MailServerConfig, message: OutgoingMessage) = withContext(Dispatchers.IO) {
        val plain = Socket(config.host, config.port)
        var socket: Socket = if (config.security == MailSecurity.TLS) {
            (tlsFactory.createSocket(plain, config.host, config.port, true) as SSLSocket)
                .verifyingHostname().apply { startHandshake() }
        } else {
            plain
        }
        var reader = BufferedReader(InputStreamReader(socket.inputStream, Charsets.UTF_8))
        var out: OutputStream = socket.outputStream

        fun read(): String {
            var line = reader.readLine() ?: throw SmtpException("Connection closed")
            // Skip continuation lines ("250-..."), keep reading until "250 ...".
            while (line.length >= 4 && line[3] == '-') line = reader.readLine() ?: break
            return line
        }

        fun expect(prefix: String, what: String) {
            val resp = read()
            if (!resp.startsWith(prefix)) throw SmtpException("$what: $resp")
        }

        fun write(line: String) {
            out.write((line + "\r\n").toByteArray(Charsets.UTF_8))
            out.flush()
        }

        // Greeting + EHLO
        expect("220", "greeting")
        write("EHLO ${localHost()}")
        expect("250", "EHLO")

        if (config.security == MailSecurity.STARTTLS) {
            write("STARTTLS")
            expect("220", "STARTTLS")
            socket = (tlsFactory.createSocket(socket, config.host, config.port, true) as SSLSocket)
                .verifyingHostname().apply { startHandshake() }
            reader = BufferedReader(InputStreamReader(socket.inputStream, Charsets.UTF_8))
            out = socket.outputStream
            write("EHLO ${localHost()}")
            expect("250", "EHLO (TLS)")
        }

        // AUTH: XOAUTH2 (OAuth bearer) when a token is present, else plain AUTH LOGIN.
        if (config.accessToken != null) {
            write("AUTH XOAUTH2 ${xoauth2Payload(config.username, config.accessToken)}")
            val resp = read()
            if (!resp.startsWith("235")) {
                // A rejected token comes back as "334 <base64 error>"; reply with an empty
                // line so the server can finish (with its 535), then report the failure.
                if (resp.startsWith("334")) { write(""); read() }
                throw SmtpException("AUTH XOAUTH2: $resp")
            }
        } else {
            write("AUTH LOGIN")
            expect("334", "AUTH")
            write(base64(config.username))
            expect("334", "AUTH user")
            write(base64(config.password))
            expect("235", "AUTH password")
        }

        // Envelope
        write("MAIL FROM:<${addressOnly(message.from)}>")
        expect("250", "MAIL FROM")
        (message.to + message.cc + message.bcc).forEach { recipient ->
            write("RCPT TO:<${addressOnly(recipient)}>")
            expect("250", "RCPT TO")
        }

        // Data
        write("DATA")
        expect("354", "DATA")
        val mime = buildMime(message)
        mime.split("\r\n").forEach { line ->
            // Dot-stuffing: a line starting with '.' must be doubled.
            out.write(((if (line.startsWith(".")) ".$line" else line) + "\r\n").toByteArray(Charsets.UTF_8))
        }
        out.write(".\r\n".toByteArray(Charsets.UTF_8))
        out.flush()
        expect("250", "message body")

        runCatching { write("QUIT") }
        runCatching { socket.close() }
        Unit
    }

    private fun buildMime(m: OutgoingMessage): String = OutgoingMime.build(m)

    private fun addressOnly(address: String): String {
        val lt = address.indexOf('<')
        return if (lt >= 0) address.substring(lt + 1).substringBefore('>').trim() else address.trim()
    }

    private fun localHost(): String = "[127.0.0.1]"

    private fun base64(s: String): String = Base64.getEncoder().encodeToString(s.toByteArray(Charsets.UTF_8))

    private companion object {
        val tlsFactory: SSLSocketFactory = SSLSocketFactory.getDefault() as SSLSocketFactory
    }
}

/** Builds the RFC 5322 message for both SMTP submission and IMAP APPEND. */
object OutgoingMime {
    fun build(m: OutgoingMessage): String {
        val date = ZonedDateTime.ofInstant(
            java.time.Instant.ofEpochMilli(m.dateMillis),
            java.time.ZoneOffset.UTC,
        ).format(DateTimeFormatter.RFC_1123_DATE_TIME)
        return buildString {
            append("From: ${headerSafe(m.from)}\r\n")
            append("To: ${m.to.joinToString(", ") { headerSafe(it) }}\r\n")
            if (m.cc.isNotEmpty()) append("Cc: ${m.cc.joinToString(", ") { headerSafe(it) }}\r\n")
            append("Subject: ${encodeHeader(m.subject)}\r\n")
            append("Date: $date\r\n")
            append("Message-ID: <${headerSafe(m.messageId.trim('<', '>'))}>\r\n")
            m.inReplyTo?.let { append("In-Reply-To: <${headerSafe(it.trim('<', '>'))}>\r\n") }
            m.references?.let { append("References: ${headerSafe(it)}\r\n") }
            append("MIME-Version: 1.0\r\n")
            val bodyContent = m.html ?: m.body
            val bodyType = if (m.html != null) "text/html" else "text/plain"
            if (m.attachments.isEmpty()) {
                append("Content-Type: $bodyType; charset=utf-8\r\n")
                append("Content-Transfer-Encoding: base64\r\n")
                append("\r\n")
                append(base64(bodyContent.toByteArray(Charsets.UTF_8)))
            } else {
                val boundary = "----sterna_${m.messageId.filter { it.isLetterOrDigit() }.take(24)}"
                append("Content-Type: multipart/mixed; boundary=\"$boundary\"\r\n\r\n")
                append("--$boundary\r\n")
                append("Content-Type: $bodyType; charset=utf-8\r\n")
                append("Content-Transfer-Encoding: base64\r\n\r\n")
                append(base64(bodyContent.toByteArray(Charsets.UTF_8)))
                append("\r\n")
                for (att in m.attachments) {
                    val safeName = headerSafe(att.name).replace("\"", "")
                    val safeType = headerSafe(att.type).replace("\"", "")
                    append("--$boundary\r\n")
                    append("Content-Type: $safeType; name=\"$safeName\"\r\n")
                    append("Content-Transfer-Encoding: base64\r\n")
                    append("Content-Disposition: attachment; filename=\"$safeName\"\r\n\r\n")
                    append(base64(att.bytes))
                    append("\r\n")
                }
                append("--$boundary--\r\n")
            }
        }
    }

    private fun base64(bytes: ByteArray): String =
        Base64.getMimeEncoder().encodeToString(bytes).replace("\n", "\r\n")

    /**
     * Strip CR/LF (and other control chars) from a structured header value so an
     * attacker-influenced address/Message-ID/References cannot smuggle extra headers
     * (e.g. a hidden Bcc:) or split the message. Reply/forward fields can echo a parsed
     * Message-ID/References straight from a hostile incoming message, so this is the sink
     * that must be clean.
     */
    private fun headerSafe(value: String): String =
        value.filterNot { it == '\r' || it == '\n' || it.code < 32 }

    /** RFC 2047-encode a header value if it contains non-ASCII OR control chars (CR/LF). */
    private fun encodeHeader(value: String): String =
        if (value.all { it.code in 32..126 }) {
            value
        } else {
            "=?utf-8?B?${Base64.getEncoder().encodeToString(value.toByteArray(Charsets.UTF_8))}?="
        }
}
