package app.jmail.core.imap

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.BufferedReader
import java.io.InputStreamReader
import java.io.OutputStream
import java.net.Socket
import java.time.ZonedDateTime
import java.time.format.DateTimeFormatter
import java.util.Base64
import javax.net.ssl.SSLSocket
import javax.net.ssl.SSLSocketFactory

class SmtpException(message: String) : Exception(message)

/** A message to submit over SMTP. Addresses are bare "name <addr>" or "addr" strings. */
data class OutgoingMessage(
    val from: String,
    val to: List<String>,
    val cc: List<String> = emptyList(),
    val subject: String,
    val body: String,
    val inReplyTo: String? = null,
    val references: String? = null,
    /** RFC 5322 Message-ID (without angle brackets); generated by the caller. */
    val messageId: String,
    /** Epoch millis for the Date header. */
    val dateMillis: Long,
)

/** Minimal SMTP submission client (EHLO, optional STARTTLS, AUTH, MAIL/RCPT/DATA). */
class SmtpClient {
    suspend fun send(config: MailServerConfig, message: OutgoingMessage) = withContext(Dispatchers.IO) {
        val plain = Socket(config.host, config.port)
        var socket: Socket = if (config.security == MailSecurity.TLS) {
            (tlsFactory.createSocket(plain, config.host, config.port, true) as SSLSocket).apply { startHandshake() }
        } else {
            plain
        }
        var reader = BufferedReader(InputStreamReader(socket.inputStream, Charsets.UTF_8))
        var out: OutputStream = socket.outputStream

        fun read(): String {
            var line = reader.readLine() ?: throw SmtpException("Connection closed")
            // Skip continuation lines ("250-..."), keep reading until "250 ...".
            while (line.length >= 4 && line[3] == '-') line = reader.readLine() ?: break
            return line
        }

        fun expect(prefix: String, what: String) {
            val resp = read()
            if (!resp.startsWith(prefix)) throw SmtpException("$what: $resp")
        }

        fun write(line: String) {
            out.write((line + "\r\n").toByteArray(Charsets.UTF_8))
            out.flush()
        }

        // Greeting + EHLO
        expect("220", "greeting")
        write("EHLO ${localHost()}")
        expect("250", "EHLO")

        if (config.security == MailSecurity.STARTTLS) {
            write("STARTTLS")
            expect("220", "STARTTLS")
            socket = (tlsFactory.createSocket(socket, config.host, config.port, true) as SSLSocket).apply { startHandshake() }
            reader = BufferedReader(InputStreamReader(socket.inputStream, Charsets.UTF_8))
            out = socket.outputStream
            write("EHLO ${localHost()}")
            expect("250", "EHLO (TLS)")
        }

        // AUTH LOGIN
        write("AUTH LOGIN")
        expect("334", "AUTH")
        write(base64(config.username))
        expect("334", "AUTH user")
        write(base64(config.password))
        expect("235", "AUTH password")

        // Envelope
        write("MAIL FROM:<${addressOnly(message.from)}>")
        expect("250", "MAIL FROM")
        (message.to + message.cc).forEach { recipient ->
            write("RCPT TO:<${addressOnly(recipient)}>")
            expect("250", "RCPT TO")
        }

        // Data
        write("DATA")
        expect("354", "DATA")
        val mime = buildMime(message)
        mime.split("\r\n").forEach { line ->
            // Dot-stuffing: a line starting with '.' must be doubled.
            out.write(((if (line.startsWith(".")) ".$line" else line) + "\r\n").toByteArray(Charsets.UTF_8))
        }
        out.write(".\r\n".toByteArray(Charsets.UTF_8))
        out.flush()
        expect("250", "message body")

        runCatching { write("QUIT") }
        runCatching { socket.close() }
        Unit
    }

    private fun buildMime(m: OutgoingMessage): String = OutgoingMime.build(m)

    private fun addressOnly(address: String): String {
        val lt = address.indexOf('<')
        return if (lt >= 0) address.substring(lt + 1).substringBefore('>').trim() else address.trim()
    }

    private fun localHost(): String = "[127.0.0.1]"

    private fun base64(s: String): String = Base64.getEncoder().encodeToString(s.toByteArray(Charsets.UTF_8))

    private companion object {
        val tlsFactory: SSLSocketFactory = SSLSocketFactory.getDefault() as SSLSocketFactory
    }
}

/** Builds the RFC 5322 message for both SMTP submission and IMAP APPEND. */
object OutgoingMime {
    fun build(m: OutgoingMessage): String {
        val date = ZonedDateTime.ofInstant(
            java.time.Instant.ofEpochMilli(m.dateMillis),
            java.time.ZoneOffset.UTC,
        ).format(DateTimeFormatter.RFC_1123_DATE_TIME)
        return buildString {
            append("From: ${m.from}\r\n")
            append("To: ${m.to.joinToString(", ")}\r\n")
            if (m.cc.isNotEmpty()) append("Cc: ${m.cc.joinToString(", ")}\r\n")
            append("Subject: ${encodeHeader(m.subject)}\r\n")
            append("Date: $date\r\n")
            append("Message-ID: <${m.messageId}>\r\n")
            m.inReplyTo?.let { append("In-Reply-To: <${it.trim('<', '>')}>\r\n") }
            m.references?.let { append("References: $it\r\n") }
            append("MIME-Version: 1.0\r\n")
            append("Content-Type: text/plain; charset=utf-8\r\n")
            append("Content-Transfer-Encoding: base64\r\n")
            append("\r\n")
            append(Base64.getMimeEncoder().encodeToString(m.body.toByteArray(Charsets.UTF_8)).replace("\n", "\r\n"))
        }
    }

    /** RFC 2047-encode a header value if it contains non-ASCII. */
    private fun encodeHeader(value: String): String =
        if (value.all { it.code in 32..126 }) {
            value
        } else {
            "=?utf-8?B?${Base64.getEncoder().encodeToString(value.toByteArray(Charsets.UTF_8))}?="
        }
}
