"""Calendar fixtures.

Times are given as UTC hour and minute, and offsets are in days from the run date, so
the seeded calendar is always sitting around "now" no matter when it is re-run. All-day
entries use a date value rather than a time, which is a different code path in every
calendar client and therefore worth having in the fixture.

Three of these deliberately exercise iTIP: one plain invitation, one that is rescheduled
after the fact (same UID, SEQUENCE bumped), and one that is cancelled. The matching mail
is generated from the same rows, so the invitation in the inbox and the entry in the
calendar can never drift apart.
"""

from __future__ import annotations

# offset  : days from today, negative is the past
# start   : (hour, minute) UTC, ignored when all_day
# minutes : duration
EVENTS: list[dict] = [
    # --- recurring ---------------------------------------------------------------
    {
        "uid": "climbing-weekly",
        "summary": "Climbing with Jules",
        "location": "Northline Climbing",
        "offset": -28,
        "start": (22, 30),
        "minutes": 90,
        "rrule": "FREQ=WEEKLY;BYDAY=TH",
        "categories": ["Personal"],
        "alarm": 60,
    },
    {
        "uid": "standup-daily",
        "summary": "Platform standup",
        "location": "Video",
        "offset": -30,
        "start": (13, 30),
        "minutes": 15,
        "rrule": "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR;COUNT=60",
        "categories": ["Work"],
    },
    {
        "uid": "one-to-one-paloma",
        "summary": "1:1 with Paloma",
        "location": "Room 2A",
        "offset": -21,
        "start": (15, 0),
        "minutes": 30,
        "rrule": "FREQ=WEEKLY;BYDAY=MO",
        "organizer": "paloma",
        "attendees": ["paloma"],
        "categories": ["Work"],
        "alarm": 10,
    },
    {
        "uid": "book-club-monthly",
        "summary": "Book club",
        "location": "Iris's place",
        "offset": -12,
        "start": (20, 0),
        "minutes": 120,
        "rrule": "FREQ=MONTHLY;BYDAY=3SU",
        "categories": ["Personal"],
    },
    # --- work, with attendees ------------------------------------------------------
    {
        "uid": "q3-platform-review",
        "summary": "Q3 platform review",
        "location": "Room 4B and video",
        "description": "Deck is final. Slides 6 and 7 are the ingest numbers.",
        "offset": -2,
        "start": (14, 0),
        "minutes": 60,
        "organizer": "paloma",
        "attendees": ["paloma", "nadia", "malcolm", "sam"],
        "categories": ["Work"],
        "alarm": 15,
        "itip": "request",
    },
    {
        "uid": "systems-design-interview",
        "summary": "Interview: systems design (candidate 1)",
        "location": "Video",
        "description": "Scorecard was sent in advance. Read it before, not after.",
        "offset": 1,
        "start": (15, 0),
        "minutes": 60,
        "organizer": "ellen",
        "attendees": ["ellen"],
        "categories": ["Work"],
        "alarm": 15,
        "itip": "request",
    },
    {
        "uid": "kestrel-cutover-call",
        "summary": "Kestrel cutover call",
        "location": "Video",
        "description": "Moved from the 24th at Rafael's request. Same agenda.",
        "offset": 8,
        "start": (13, 0),
        "minutes": 45,
        "organizer": "raf",
        "attendees": ["raf", "dmitri", "grace"],
        "categories": ["Work"],
        "sequence": 1,
        "itip": "reschedule",
        "was": "the 24th at 09:00",
    },
    {
        "uid": "vendor-briefing-cancelled",
        "summary": "Vendor briefing: Halcyon",
        "location": "Room 1C",
        "offset": 4,
        "start": (16, 0),
        "minutes": 60,
        "organizer": "malcolm",
        "attendees": ["malcolm", "paloma"],
        "status": "CANCELLED",
        "sequence": 2,
        "categories": ["Work"],
        "itip": "cancel",
    },
    {
        "uid": "access-review-deadline",
        "summary": "Access review closes",
        "offset": 7,
        "all_day": True,
        "days": 1,
        "categories": ["Work"],
        "transparent": True,
    },
    {
        "uid": "roadmap-planning",
        "summary": "Q4 roadmap planning",
        "location": "Room 4B",
        "description": "Bring the headcount view in writing.",
        "offset": 11,
        "start": (14, 0),
        "minutes": 120,
        "organizer": "nadia",
        "attendees": ["nadia", "paloma", "sam", "hana"],
        "categories": ["Work"],
        "alarm": 30,
    },
    {
        "uid": "incident-review-2291",
        "summary": "Incident review INC-2291",
        "location": "Video",
        "offset": -9,
        "start": (17, 0),
        "minutes": 45,
        "organizer": "tomas",
        "attendees": ["tomas", "dmitri", "sam"],
        "categories": ["Work"],
    },
    {
        "uid": "guest-lecture",
        "summary": "Guest lecture: applied data seminar",
        "location": "Ashvale State, Room 214",
        "description": "50 minutes plus questions. Second half is on choosing what to measure.",
        "offset": 19,
        "start": (18, 0),
        "minutes": 90,
        "organizer": "prof",
        "attendees": ["prof"],
        "categories": ["Work"],
        "alarm": 120,
    },
    {
        "uid": "on-call-week",
        "summary": "On call",
        "offset": 21,
        "all_day": True,
        "days": 7,
        "categories": ["Work"],
        "transparent": True,
    },
    {
        "uid": "backfill-window",
        "summary": "Kestrel backfill window (do not retry if it fails)",
        "offset": 8,
        "start": (6, 0),
        "minutes": 240,
        "categories": ["Work"],
    },
    {
        "uid": "weekly-export-check",
        "summary": "Verify weekly export",
        "offset": -25,
        "start": (12, 0),
        "minutes": 20,
        "rrule": "FREQ=WEEKLY;BYDAY=FR",
        "categories": ["Work"],
    },
    {
        "uid": "design-review-empty-states",
        "summary": "Design review: empty states",
        "location": "Video",
        "offset": -1,
        "start": (16, 30),
        "minutes": 45,
        "organizer": "hana",
        "attendees": ["hana", "nadia"],
        "categories": ["Work"],
    },
    # --- personal ------------------------------------------------------------------
    {
        "uid": "noors-birthday-party",
        "summary": "Noor's birthday party",
        "location": "Mei and Hugo's",
        "description": "Bring the geology kit. Do not bring noodles.",
        "offset": 12,
        "start": (19, 0),
        "minutes": 180,
        "categories": ["Family"],
        "alarm": 1440,
    },
    {
        "uid": "flight-out-seattle",
        "summary": "Flight ASH to SEA",
        "location": "Ashvale Regional",
        "offset": 11,
        "start": (22, 45),
        "minutes": 350,
        "categories": ["Travel"],
        "alarm": 180,
    },
    {
        "uid": "flight-back-seattle",
        "summary": "Flight SEA to ASH",
        "location": "Seattle Tacoma",
        "offset": 14,
        "start": (23, 20),
        "minutes": 300,
        "categories": ["Travel"],
        "alarm": 180,
    },
    {
        "uid": "stockholm-trip",
        "summary": "Stockholm, design week",
        "location": "Stockholm",
        "offset": 27,
        "all_day": True,
        "days": 4,
        "categories": ["Travel"],
    },
    {
        "uid": "cabin-weekend",
        "summary": "Cabin weekend (provisional)",
        "location": "Ridgemont",
        "offset": 55,
        "all_day": True,
        "days": 3,
        "categories": ["Personal"],
        "transparent": True,
    },
    {
        "uid": "nutmeg-vet",
        "summary": "Nutmeg: rabies booster",
        "location": "Brookvale Veterinary",
        "description": "Mention the back left limp. They have allowed extra time.",
        "offset": 7,
        "start": (20, 15),
        "minutes": 30,
        "categories": ["Personal"],
        "alarm": 120,
    },
    {
        "uid": "dentist-checkup",
        "summary": "Dentist, six month check",
        "location": "Cornerstone Dental",
        "offset": 33,
        "start": (13, 30),
        "minutes": 45,
        "categories": ["Personal"],
        "alarm": 1440,
    },
    {
        "uid": "shoulder-rehab-block",
        "summary": "Shoulder rehab set",
        "offset": -18,
        "start": (11, 30),
        "minutes": 25,
        "rrule": "FREQ=WEEKLY;BYDAY=MO,WE,FR;COUNT=18",
        "categories": ["Personal"],
    },
    {
        "uid": "manda-wedding",
        "summary": "Amanda and Ola's wedding",
        "location": "Charleston",
        "offset": 243,
        "all_day": True,
        "days": 1,
        "categories": ["Personal"],
    },
    {
        "uid": "mom-birthday",
        "summary": "Mom's birthday",
        "offset": 34,
        "all_day": True,
        "days": 1,
        "rrule": "FREQ=YEARLY",
        "categories": ["Family"],
        "transparent": True,
        "alarm": 2880,
    },
    {
        "uid": "dinner-with-bea",
        "summary": "Dinner with Bea",
        "location": "Optimist Hall",
        "offset": 3,
        "start": (23, 0),
        "minutes": 120,
        "categories": ["Personal"],
    },
    {
        "uid": "roofer-visit",
        "summary": "Roofer, back bedroom",
        "location": "Home",
        "offset": -37,
        "start": (12, 0),
        "minutes": 240,
        "categories": ["Home"],
    },
    {
        "uid": "car-service",
        "summary": "Car in at Camden Auto",
        "location": "Camden Auto",
        "offset": -20,
        "start": (12, 30),
        "minutes": 60,
        "categories": ["Home"],
    },
    {
        "uid": "strataconf",
        "summary": "StrataConf",
        "location": "Atlanta",
        "offset": 40,
        "all_day": True,
        "days": 3,
        "categories": ["Work", "Travel"],
    },
]
