"""The cast: who Avery Chen knows, and who mails her.

Every address in here is under a domain this project controls or a domain reserved for
documentation, so a seeded mailbox can never send real mail to a real stranger if
something is replied to by accident.

Contacts are keyed by a short handle. The mail corpus and the address book both draw
from this one list, so a sender in the message list is a person you can open in Contacts,
which is the whole point of seeding both at once.
"""

from __future__ import annotations

OWNER_NAME = "Avery Chen"
OWNER_HANDLE = "avery"

# The employer. Used for work threads, the address book, and calendar attendees.
COMPANY = "Northwind Analytics"
COMPANY_DOMAIN = "northwind.example"

CONTACTS: list[dict] = [
    # --- Work: Northwind Analytics -------------------------------------------------
    {
        "handle": "paloma",
        "first": "Paloma",
        "last": "Raghunathan",
        "org": COMPANY,
        "title": "Director of Data Platform",
        "emails": [("work", "paloma.raghunathan@northwind.example")],
        "phones": [("work", "+1-717-555-0142"), ("cell", "+1-717-555-0188")],
        "address": ("work", "410 Halstead Street, Suite 900", "Ashvale", "PA", "17036", "USA"),
        "note": "My manager. Prefers a written summary before any meeting.",
        "categories": ["Work"],
        "photo": True,
    },
    {
        "handle": "dmitri",
        "first": "Dmitri",
        "last": "Sokolov",
        "org": COMPANY,
        "title": "Staff Engineer, Ingest",
        "emails": [("work", "dmitri.sokolov@northwind.example")],
        "phones": [("work", "+1-717-555-0119")],
        "note": "Owns the ingest pipeline. On UTC+1 most of the summer.",
        "categories": ["Work"],
        "photo": True,
    },
    {
        "handle": "nadia",
        "first": "Nadia",
        "last": "Okafor",
        "org": COMPANY,
        "title": "Product Manager",
        "emails": [
            ("work", "nadia.okafor@northwind.example"),
            ("home", "nadia.okafor@example.net"),
        ],
        "phones": [("cell", "+1-980-555-0173")],
        "categories": ["Work"],
        "photo": True,
    },
    {
        "handle": "tomas",
        "first": "Tomas",
        "last": "Beckett",
        "org": COMPANY,
        "title": "Site Reliability Engineer",
        "emails": [("work", "tomas.beckett@northwind.example")],
        "phones": [("work", "+1-717-555-0155")],
        "note": "On call rotation, week 3 of 4.",
        "categories": ["Work"],
        "photo": True,
    },
    {
        "handle": "hana",
        "first": "Hana",
        "last": "Lindqvist",
        "org": COMPANY,
        "title": "Design Lead",
        "emails": [("work", "hana.lindqvist@northwind.example")],
        "phones": [("cell", "+46 8 555 0121")],
        "address": ("work", "Kungsgatan 12", "Stockholm", "", "111 35", "Sweden"),
        "categories": ["Work"],
        "photo": True,
    },
    {
        "handle": "malcolm",
        "first": "Malcolm",
        "last": "Ellery",
        "org": COMPANY,
        "title": "Finance Business Partner",
        "emails": [("work", "malcolm.ellery@northwind.example")],
        "phones": [("work", "+1-717-555-0164")],
        "categories": ["Work"],
        "photo": False,
    },
    {
        "handle": "yuki",
        "first": "Yuki",
        "last": "Tanaka",
        "org": COMPANY,
        "title": "Data Scientist",
        "emails": [("work", "yuki.tanaka@northwind.example")],
        "phones": [("cell", "+81 3 5555 0198")],
        "categories": ["Work"],
        "photo": True,
    },
    {
        "handle": "olu",
        "first": "Oluwaseun",
        "last": "Adeyemi",
        "org": COMPANY,
        "title": "Security Engineer",
        "emails": [("work", "oluwaseun.adeyemi@northwind.example")],
        "phones": [("work", "+1-717-555-0107")],
        "note": "Runs the quarterly access review. Answer it the first time.",
        "categories": ["Work"],
        "photo": True,
    },
    {
        "handle": "ellen",
        "first": "Ellen",
        "last": "Ваасе",
        "org": COMPANY,
        "title": "Recruiting Coordinator",
        "emails": [("work", "ellen.vaase@northwind.example")],
        "phones": [("work", "+1-717-555-0133")],
        "note": "Name deliberately carries Cyrillic characters: checks non-Latin rendering.",
        "categories": ["Work"],
        "photo": False,
    },
    {
        "handle": "raf",
        "first": "Rafael",
        "last": "Duarte",
        "org": "Kestrel Consulting",
        "title": "Principal Consultant",
        "emails": [("work", "rafael.duarte@kestrel.example")],
        "phones": [("work", "+55 11 5555 0144")],
        "address": ("work", "Av. Paulista 1500", "Sao Paulo", "SP", "01310-200", "Brazil"),
        "categories": ["Work", "Vendors"],
        "photo": True,
    },
    {
        "handle": "grace",
        "first": "Grace",
        "last": "Okonkwo",
        "org": "Harbourline Legal",
        "title": "Contracts Counsel",
        "emails": [("work", "g.okonkwo@harbourline.example")],
        "phones": [("work", "+1-212-555-0190")],
        "categories": ["Work", "Vendors"],
        "photo": False,
    },
    {
        "handle": "sam",
        "first": "Sam",
        "last": "Whitfield",
        "org": COMPANY,
        "title": "Engineering Manager",
        "emails": [("work", "sam.whitfield@northwind.example")],
        "phones": [("work", "+1-717-555-0126")],
        "categories": ["Work"],
        "photo": True,
    },
    # --- Friends -------------------------------------------------------------------
    {
        "handle": "jules",
        "first": "Jules",
        "last": "Marchetti",
        "emails": [("home", "jules.marchetti@example.net")],
        "phones": [("cell", "+1-717-555-0211")],
        "address": ("home", "88 Brookvale Court", "Ashvale", "PA", "17112", "USA"),
        "note": "Climbing partner. Thursdays at the gym unless it rains.",
        "birthday": "--0314",
        "categories": ["Friends"],
        "photo": True,
    },
    {
        "handle": "bea",
        "first": "Beatrice",
        "last": "Nguyen",
        "emails": [("home", "bea.nguyen@example.net"), ("work", "b.nguyen@meridian.example")],
        "phones": [("cell", "+1-717-555-0224")],
        "birthday": "--0702",
        "categories": ["Friends"],
        "photo": True,
    },
    {
        "handle": "corin",
        "first": "Corin",
        "last": "Balogh",
        "emails": [("home", "corin.balogh@example.net")],
        "phones": [("cell", "+36 1 555 0177")],
        "note": "Uses they/them.",
        "categories": ["Friends"],
        "photo": True,
    },
    {
        "handle": "darius",
        "first": "Darius",
        "last": "Pritchard",
        "emails": [("home", "darius.pritchard@example.net")],
        "phones": [("cell", "+1-828-555-0138")],
        "address": ("home", "12 Cedar Ridge Road", "Ridgemont", "PA", "16833", "USA"),
        "birthday": "--1129",
        "categories": ["Friends"],
        "photo": True,
    },
    {
        "handle": "iris",
        "first": "Iris",
        "last": "Kovalenko",
        "emails": [("home", "iris.kovalenko@example.net")],
        "phones": [("cell", "+1-717-555-0245")],
        "categories": ["Friends", "Book club"],
        "photo": True,
    },
    {
        "handle": "theo",
        "first": "Theo",
        "last": "Abara",
        "emails": [("home", "theo.abara@example.net")],
        "phones": [("cell", "+1-919-555-0182")],
        "categories": ["Friends", "Book club"],
        "photo": False,
    },
    {
        "handle": "manda",
        "first": "Amanda",
        "last": "Reyes-Ortiz",
        "emails": [("home", "amanda.reyes@example.net")],
        "phones": [("cell", "+1-717-555-0259"), ("home", "+1-717-555-0260")],
        "birthday": "--0508",
        "categories": ["Friends"],
        "photo": True,
    },
    {
        "handle": "kwame",
        "first": "Kwame",
        "last": "Boateng",
        "emails": [("home", "kwame.boateng@example.net")],
        "phones": [("cell", "+233 30 555 0116")],
        "categories": ["Friends"],
        "photo": True,
    },
    {
        "handle": "lena",
        "first": "Lena",
        "last": "Fitzgerald",
        "emails": [("home", "lena.fitzgerald@example.net")],
        "phones": [("cell", "+1-717-555-0271")],
        "categories": ["Friends", "Book club"],
        "photo": False,
    },
    # --- Family --------------------------------------------------------------------
    {
        "handle": "mom",
        "first": "Wei",
        "last": "Chen",
        "nickname": "Mom",
        "emails": [("home", "wei.chen@example.net")],
        "phones": [("home", "+1-206-555-0104"), ("cell", "+1-206-555-0105")],
        "address": ("home", "2214 Fremont Avenue N", "Seattle", "WA", "98103", "USA"),
        "birthday": "19580921",
        "categories": ["Family"],
        "photo": True,
    },
    {
        "handle": "dad",
        "first": "Robert",
        "last": "Chen",
        "nickname": "Dad",
        "emails": [("home", "robert.chen@example.net")],
        "phones": [("cell", "+1-206-555-0106")],
        "address": ("home", "2214 Fremont Avenue N", "Seattle", "WA", "98103", "USA"),
        "birthday": "19560211",
        "categories": ["Family"],
        "photo": True,
    },
    {
        "handle": "mei",
        "first": "Mei",
        "last": "Chen-Duval",
        "emails": [("home", "mei.chenduval@example.net")],
        "phones": [("cell", "+1-206-555-0117")],
        "note": "Sister. Two kids, Noor and Elias.",
        "birthday": "19910630",
        "categories": ["Family"],
        "photo": True,
    },
    {
        "handle": "hugo",
        "first": "Hugo",
        "last": "Duval",
        "emails": [("home", "hugo.duval@example.net")],
        "phones": [("cell", "+1-206-555-0118")],
        "note": "Brother in law.",
        "categories": ["Family"],
        "photo": False,
    },
    {
        "handle": "aunt",
        "first": "Lilian",
        "last": "Chen",
        "emails": [("home", "lilian.chen@example.net")],
        "phones": [("home", "+1-415-555-0193")],
        "address": ("home", "77 Balboa Street", "San Francisco", "CA", "94118", "USA"),
        "birthday": "19521204",
        "categories": ["Family"],
        "photo": True,
    },
    # --- Services and appointments -------------------------------------------------
    {
        "handle": "dentist",
        "first": "Nasrin",
        "last": "Haddad",
        "org": "Cornerstone Dental",
        "title": "DDS",
        "emails": [("work", "front.desk@queencitydental.example")],
        "phones": [("work", "+1-717-555-0300")],
        "address": ("work", "1330 Weatherby Boulevard", "Ashvale", "PA", "17057", "USA"),
        "categories": ["Health"],
        "photo": False,
    },
    {
        "handle": "vet",
        "first": "Owen",
        "last": "Castellanos",
        "org": "Brookvale Veterinary",
        "title": "DVM",
        "emails": [("work", "appointments@pmvet.example")],
        "phones": [("work", "+1-717-555-0311")],
        "address": ("work", "1409 Ferndale Avenue", "Ashvale", "PA", "17112", "USA"),
        "note": "Sees Nutmeg. Rabies booster due each spring.",
        "categories": ["Health"],
        "photo": False,
    },
    {
        "handle": "landlord",
        "first": "Ruth",
        "last": "Halvorsen",
        "org": "Halvorsen Property",
        "emails": [("work", "ruth@halvorsenproperty.example")],
        "phones": [("work", "+1-717-555-0322"), ("cell", "+1-717-555-0323")],
        "categories": ["Home"],
        "photo": False,
    },
    {
        "handle": "mechanic",
        "first": "Ade",
        "last": "Salako",
        "org": "Camden Auto",
        "emails": [("work", "service@southendauto.example")],
        "phones": [("work", "+1-717-555-0334")],
        "address": ("work", "2500 Larkin Boulevard", "Ashvale", "PA", "17057", "USA"),
        "categories": ["Home"],
        "photo": False,
    },
    {
        "handle": "pharmacy",
        "first": "Ravenwood",
        "last": "Pharmacy",
        "org": "Ravenwood Pharmacy",
        "emails": [("work", "refills@ravenwoodrx.example")],
        "phones": [("work", "+1-717-555-0345")],
        "categories": ["Health"],
        "photo": False,
    },
    {
        "handle": "trainer",
        "first": "Sofia",
        "last": "Marchand",
        "org": "Northline Climbing",
        "title": "Coach",
        "emails": [("work", "sofia@northlineclimbing.example")],
        "phones": [("cell", "+1-717-555-0356")],
        "categories": ["Health"],
        "photo": True,
    },
    # --- Loose professional contacts -----------------------------------------------
    {
        "handle": "recruiter",
        "first": "Gideon",
        "last": "Marsh",
        "org": "Ardent Talent",
        "title": "Technical Recruiter",
        "emails": [("work", "gideon.marsh@ardenttalent.example")],
        "phones": [("work", "+1-646-555-0177")],
        "note": "Cold outreach, twice a quarter, always the same role.",
        "categories": ["Recruiters"],
        "photo": False,
    },
    {
        "handle": "editor",
        "first": "Constance",
        "last": "Iyer",
        "org": "Ledger Quarterly",
        "title": "Features Editor",
        "emails": [("work", "constance.iyer@ledgerquarterly.example")],
        "phones": [("work", "+44 20 5555 0128")],
        "categories": ["Press"],
        "photo": True,
    },
    {
        "handle": "prof",
        "first": "Aurelio",
        "last": "Bennett",
        "org": "Ashvale State",
        "title": "Associate Professor",
        "emails": [("work", "abennett@uncc.example")],
        "phones": [("work", "+1-717-555-0367")],
        "note": "Guest lecture contact. Answers slowly in term time.",
        "categories": ["Work"],
        "photo": False,
    },
    {
        "handle": "neighbour",
        "first": "Perpetua",
        "last": "Nwosu",
        "emails": [("home", "perpetua.nwosu@example.net")],
        "phones": [("cell", "+1-717-555-0378")],
        "note": "Next door. Has the spare key.",
        "categories": ["Home"],
        "photo": True,
    },
    {
        "handle": "accountant",
        "first": "Desmond",
        "last": "Farrow",
        "org": "Farrow and Blake CPA",
        "emails": [("work", "d.farrow@farrowblake.example")],
        "phones": [("work", "+1-717-555-0389")],
        "categories": ["Finance"],
        "photo": False,
    },
    {
        "handle": "insurance",
        "first": "Wren",
        "last": "Ashworth",
        "org": "Cardinal Mutual",
        "title": "Agent",
        "emails": [("work", "wren.ashworth@cardinalmutual.example")],
        "phones": [("work", "+1-717-555-0390")],
        "categories": ["Finance"],
        "photo": False,
    },
    {
        "handle": "photog",
        "first": "Ingrid",
        "last": "Sorensen",
        "org": "Sorensen Studio",
        "emails": [("work", "hello@sorensenstudio.example")],
        "phones": [("cell", "+45 33 555 0142")],
        "categories": ["Friends"],
        "photo": True,
    },
    {
        "handle": "travel",
        "first": "Bashir",
        "last": "Rahimi",
        "org": "Waypoint Travel",
        "emails": [("work", "bashir@waypointtravel.example")],
        "phones": [("work", "+1-717-555-0401")],
        "categories": ["Travel"],
        "photo": False,
    },
]

# Senders that are software, not people. They never go in the address book.
ROBOTS: dict[str, tuple[str, str]] = {
    "brief": ("The Morning Brief", "digest@morningbrief.example"),
    "devweekly": ("Dev Weekly", "issues@devweekly.example"),
    "forge": ("Forge", "notifications@forge.example"),
    "meridian": ("Meridian Credit Union", "alerts@meridiancu.example"),
    "ridgeline": ("Ridgeline Outfitters", "orders@ridgeline.example"),
    "coffee": ("Corner Coffee Roasters", "hello@cornercoffee.example"),
    "shipping": ("Parcelway Tracking", "tracking@parcelway.example"),
    "calendar": ("Northwind Calendar", "calendar@northwind.example"),
    "status": ("Northwind Status", "status@northwind.example"),
    "utility": ("Piedmont Power", "billing@piedmontpower.example"),
    "library": ("Halesworth County Library", "notices@halesworthlibrary.example"),
    "gym": ("Northline Climbing", "no-reply@northlineclimbing.example"),
    "streaming": ("Lumen Play", "billing@lumenplay.example"),
    "conf": ("StrataConf", "registration@strataconf.example"),
}

# Junk. Obvious in tone, harmless in content, and all pointed at reserved domains.
SPAMMERS: list[tuple[str, str]] = [
    ("Wealth Horizons", "opportunity@wealth-horizons.example"),
    ("PRIZE NOTIFICATION DEPT", "claims@prize-notify.example"),
    ("Miranda from SEO", "miranda@rank-first-now.example"),
    ("Warranty Services", "renewals@auto-warranty-desk.example"),
    ("CryptoPulse Signals", "signals@cryptopulse-alerts.example"),
    ("HR Benefits Update", "benefits@northwlnd-analytics.example"),
    ("Package Delivery Failure", "notice@parcel-redelivery.example"),
    ("Dr. Emeka Financial", "transfer@intl-transfer-desk.example"),
    ("Single Women Nearby", "connect@meetup-tonight.example"),
]


def by_handle() -> dict[str, dict]:
    return {c["handle"]: c for c in CONTACTS}


def display(contact: dict) -> str:
    return f"{contact['first']} {contact['last']}".strip()


def primary_email(contact: dict) -> str:
    return contact["emails"][0][1]


def initials(contact: dict) -> str:
    first = contact["first"][:1]
    last = contact["last"][:1]
    return (first + last).upper()
